### ISSUE TITLE
Flush buffers on ctrl-C/kill/signals.

### ISSUE THREAD

**Issue by m-ou-se** [fusion-engineering/ipc-logger#2]

**Comment by de-vri-es** [comment]
Implemented in bbe3ddb. SIGINT and SIGTERM are now handled. They cleanly stop the loop so the writer is dropped, which should ensure the log is flushed.

Note that the log writer wasn't using a coalescing bufwriter, so I think there was nothing to flush. But now that signal handling is in place, I also switched to a coalescing bufwriter.
